busker/urls.py
from django.urls import path
from .views import RedeemView, RedeemFormView, DownloadView

app_name = 'busker'
urlpatterns = [
    path('redeem/<str:download_code>/', RedeemView.as_view(), name='redeem'),
    path('', RedeemFormView.as_view(), name='redeem_form'),
    path('download/<str:file_id>/', DownloadView.as_view(), name='download')
]

busker/templates/busker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block html_title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static 'busker/css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'busker/css/skeleton.css' %}">
  <link rel="stylesheet" href="{% static 'busker/css/busker.css' %}">
</head>
<body>
  <div class="container busker-main">
    <div class="row">
      <div class="one-column">
        <h1>{% block page_title %}Basic Page{% endblock %}</h1>
        {% block content %}

        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

busker/templates/busker/confirm_form.html
{% extends "busker/base.html" %}

{% block html_title %}Redeem Code for {{ code.batch.work.artist.name }} - {{ code.batch.work.title }}{% endblock %}
{% block page_title %}{{ code.batch.work.artist.name }} - {{ code.batch.work.title }}{% endblock %}
{% block content %}
{% if code.remaining_uses <= 0 %}
<h2>Code Expired</h2>
{% else %}
<h2>Redeem Code</h2>
{% endif %}
    {% if code.batch.work.image %}
<div class="busker-thumbnail">
        <img src="{{ code.batch.work.thumbnail.url }}" alt="{{ code.batch.work.title }}">
        </div>
    {% endif %}
<form action="{% url 'busker:redeem' form.code.value %}" method="POST">
    {% csrf_token %}
    {% if code.max_uses == 0 %}
        <p>This code entitles you to unlimited downloads.</p>
    {% elif code.remaining_uses > 0 %}
        <p>This code has {{ code.remaining_uses }} use{{ code.remaining_uses|pluralize }} left.</p>
        {{ form.as_p }}
	{% if code.batch.public_message %}
	{{ code.batch.public_message_rendered|safe }}
	{% endif %}

	<input type="submit" value="Continue">
    {% else %}
        This code has already been used.
    {% endif %}
</form>
{% endblock %}

busker/templates/busker/error.html
{% extends "busker/base.html" %} {# Use this template to display HTML errors #}
{% load i18n %}
{% block html_title %}{% trans "Error:" %} {{ title }} ({{ status }}){% endblock %}
{% block page_title %}{{ title }}{% endblock %}
{% block content %}
    {{ message }}
{% endblock %}

busker/templates/busker/file_list.html
{% extends "busker/base.html" %}
{% block html_title %}Download Files{% endblock %}
{% block page_title %}Download Files{% endblock %}
{% block content %}
<h2>{{ code.batch.work.artist.name }} - {{ code.batch.work.title }}</h2>
<table>
    <tbody>
    {% for file in code.batch.work.files.all %}
        <tr>
            <td><a href="{% url 'busker:download' file.id %}?t={{ request.session.busker_download_token }}">{{ file.filename }}</a></td>
            <td>{{ file.description }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

busker/templates/busker/redeem_form.html
{% extends "busker/base.html" %}
{% block html_title %}Redeem Code{% endblock %}
{% block page_title %}Redeem Code{% endblock %}
{% block content %}
<form action="{% url 'busker:redeem_form' %}" method="POST">
    {%  csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Redeem Code"/>
</form>
{% endblock %}